# Generated by Django 6.0.1 on 2026-01-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'کاربر عادی'), ('TEACHER', 'مدرس'), ('SUPPORT', 'پشتیبان سایت'), ('ADMIN', 'مدیر')], default='USER', max_length=10, verbose_name='نقش کاربر'),
        ),
    ]
