# Generated by Django 6.0.1 on 2026-01-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_active_code_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active_code',
            new_name='email_active_code',
        ),
    ]
