# Generated by Django 6.0.1 on 2026-01-31 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_active_code_user_email_active_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_active_code',
            new_name='activation_code',
        ),
    ]
