# Generated by Django 6.0.1 on 2026-02-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان شغل')),
                ('description', models.TextField(blank=True, verbose_name='توضیح شغل')),
                ('icon_class', models.CharField(blank=True, max_length=50, verbose_name='آیکون (کلاس FontAwesome)')),
            ],
            options={
                'verbose_name': 'شاخه شغلی',
                'verbose_name_plural': 'شاخه\u200cهای شغلی',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مهارت')),
                ('tag', models.CharField(blank=True, max_length=50, verbose_name='تگ')),
                ('description', models.TextField(verbose_name='توضیح کوتاه')),
                ('duration_hours', models.CharField(max_length=100, verbose_name='مدت زمان یادگیری')),
                ('level_value', models.PositiveIntegerField(default=0, help_text='عدد بین 0 تا 100 برای تعیین سطح مهارت', verbose_name='سطح مهارت (0 تا 100)')),
                ('icon_class', models.CharField(blank=True, max_length=50, verbose_name='آیکون (کلاس FontAwesome)')),
                ('jobs', models.ManyToManyField(related_name='skills', to='roadmap.job', verbose_name='شغل\u200cهای مرتبط')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
            },
        ),
    ]
