# Generated by Django 6.0.1 on 2026-02-01 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('beginner', 'مقدماتی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], max_length=20, unique=True, verbose_name='نام سطح')),
                ('icon_class', models.CharField(blank=True, max_length=50, verbose_name='آیکون سطح')),
                ('description', models.TextField(blank=True, verbose_name='توضیح سطح')),
            ],
            options={
                'verbose_name': 'سطح مهارت',
                'verbose_name_plural': 'سطوح مهارت',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='roadmap.skilllevel', verbose_name='سطح'),
        ),
    ]
