# Generated by Django 6.0.1 on 2026-02-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_skilllevel_skill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilllevel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skilllevel',
            name='icon_class',
        ),
    ]
