# Generated by Django 6.0.1 on 2026-01-28 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEVIO', max_length=100, verbose_name='اسم سایت')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name=' توضیح کوتاه')),
                ('about_text', models.TextField(blank=True, verbose_name='درباره ما')),
                ('goals_text', models.TextField(blank=True, verbose_name='اهداف آکادمی')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='لوگو سایت')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='آیکون سایت')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='ادرس فیسبوک')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='ادرس اینستاگرام')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='ادرس لینکدین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='home.siteinfo', verbose_name='اطلاعات سایت')),
            ],
        ),
    ]
