# Generated by Django 6.0.1 on 2026-01-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='hero_video',
            field=models.FileField(blank=True, help_text='ویدیوی پس\u200cزمینه صفحه اصلی (mp4)', null=True, upload_to='site/videos/'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/icon/', verbose_name='آیکون سایت'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/logo/', verbose_name='لوگو سایت'),
        ),
    ]
