# Generated by Django 6.0.1 on 2026-01-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_siteinfo_hero_video_alter_siteinfo_favicon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'هدف', 'verbose_name_plural': 'اهداف'},
        ),
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name': 'اطلاعات سایت', 'verbose_name_plural': 'اطلاعات سایت'},
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='email',
            field=models.EmailField(default='sudowebsite@gmail.com', max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='number',
            field=models.CharField(default='09337480645', verbose_name='تلفن'),
        ),
    ]
