# Generated by Django 6.0.1 on 2026-01-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_activity_options_alter_siteinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='site/icon/', verbose_name='آیکون سایت'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='site/logo/', verbose_name='لوگو سایت'),
        ),
    ]
