# Generated by Django 6.0.1 on 2026-01-30 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دوره')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('status', models.CharField(choices=[('REGISTRATION', 'در حال ثبت\u200cنام'), ('ONGOING', 'در حال برگزاری'), ('FINISHED', 'پایان یافته')], default='REGISTRATION', max_length=20, verbose_name='وضعیت دوره')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='تصویر دوره')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='ظرفیت دوره')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
