# Generated by Django 6.0.1 on 2026-01-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='پیش نیازهای دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='skills_after',
            field=models.TextField(blank=True, null=True, verbose_name='مهارت\u200cهای بعد از دوره'),
        ),
    ]
