# Generated by Django 6.0.1 on 2026-02-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseenrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseenrollment',
            options={'ordering': ['-created_at'], 'verbose_name': 'شاگرد', 'verbose_name_plural': 'شاگردان'},
        ),
    ]
